{"created": 1752163397.0789933, "duration": 2.769230842590332, "exitcode": 1, "root": "/home/alex/cashcow", "environment": {}, "summary": {"failed": 24, "total": 24, "collected": 24}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/test_reports.py", "type": "Module"}]}, {"nodeid": "tests/test_reports.py::TestReportGenerator", "outcome": "passed", "result": [{"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_generator_initialization", "type": "Function", "lineno": 118}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_cash_flow_chart", "type": "Function", "lineno": 133}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_revenue_breakdown_chart", "type": "Function", "lineno": 157}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_expense_breakdown_chart", "type": "Function", "lineno": 180}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_kpi_dashboard", "type": "Function", "lineno": 203}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_runway_analysis_chart", "type": "Function", "lineno": 226}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_burn_rate_chart", "type": "Function", "lineno": 249}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_export_to_csv", "type": "Function", "lineno": 272}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_export_to_excel", "type": "Function", "lineno": 296}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_export_kpis_to_json", "type": "Function", "lineno": 319}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_html_report", "type": "Function", "lineno": 349}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_pdf_report", "type": "Function", "lineno": 379}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_complete_report_package", "type": "Function", "lineno": 404}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_executive_summary", "type": "Function", "lineno": 443}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_entity_breakdown_report", "type": "Function", "lineno": 477}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_trend_analysis_report", "type": "Function", "lineno": 510}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_risk_assessment_report", "type": "Function", "lineno": 541}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_scenario_comparison_report", "type": "Function", "lineno": 574}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_custom_report_template", "type": "Function", "lineno": 623}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_error_handling", "type": "Function", "lineno": 683}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_customization_options", "type": "Function", "lineno": 733}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_automation_and_scheduling", "type": "Function", "lineno": 778}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_performance_optimization", "type": "Function", "lineno": 816}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_data_validation", "type": "Function", "lineno": 880}]}, {"nodeid": "tests/test_reports.py", "outcome": "passed", "result": [{"nodeid": "tests/test_reports.py::TestReportGenerator", "type": "Class"}]}], "tests": [{"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_generator_initialization", "lineno": 118, "outcome": "failed", "keywords": ["test_report_generator_initialization", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.0009040989971254021, "outcome": "passed"}, "call": {"duration": 0.03439878299832344, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 121, "message": "in test_report_generator_initialization"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:121: in test_report_generator_initialization\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0003746270012925379, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_cash_flow_chart", "lineno": 133, "outcome": "failed", "keywords": ["test_generate_cash_flow_chart", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.0002813180035445839, "outcome": "passed"}, "call": {"duration": 0.021253393999359105, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 136, "message": "in test_generate_cash_flow_chart"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:136: in test_generate_cash_flow_chart\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00033186699874931946, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_revenue_breakdown_chart", "lineno": 157, "outcome": "failed", "keywords": ["test_generate_revenue_breakdown_chart", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00022783700114814565, "outcome": "passed"}, "call": {"duration": 0.02171993900265079, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 160, "message": "in test_generate_revenue_breakdown_chart"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:160: in test_generate_revenue_breakdown_chart\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002815260013449006, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_expense_breakdown_chart", "lineno": 180, "outcome": "failed", "keywords": ["test_generate_expense_breakdown_chart", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00023197099653771147, "outcome": "passed"}, "call": {"duration": 0.0202388570032781, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 183, "message": "in test_generate_expense_breakdown_chart"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:183: in test_generate_expense_breakdown_chart\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002675200012163259, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_kpi_dashboard", "lineno": 203, "outcome": "failed", "keywords": ["test_generate_kpi_dashboard", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.0002307819959241897, "outcome": "passed"}, "call": {"duration": 0.020774840995727573, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 206, "message": "in test_generate_kpi_dashboard"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:206: in test_generate_kpi_dashboard\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002372310045757331, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_runway_analysis_chart", "lineno": 226, "outcome": "failed", "keywords": ["test_generate_runway_analysis_chart", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00020236100681358948, "outcome": "passed"}, "call": {"duration": 0.020141620996582787, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 229, "message": "in test_generate_runway_analysis_chart"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:229: in test_generate_runway_analysis_chart\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002603269967949018, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_burn_rate_chart", "lineno": 249, "outcome": "failed", "keywords": ["test_generate_burn_rate_chart", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00021181999909458682, "outcome": "passed"}, "call": {"duration": 0.019707699997525197, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 252, "message": "in test_generate_burn_rate_chart"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:252: in test_generate_burn_rate_chart\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00024394400679739192, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_export_to_csv", "lineno": 272, "outcome": "failed", "keywords": ["test_export_to_csv", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00019168099970556796, "outcome": "passed"}, "call": {"duration": 0.019616621000750456, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 275, "message": "in test_export_to_csv"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:275: in test_export_to_csv\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002508120014681481, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_export_to_excel", "lineno": 296, "outcome": "failed", "keywords": ["test_export_to_excel", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00021846099843969569, "outcome": "passed"}, "call": {"duration": 0.01909157000045525, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 299, "message": "in test_export_to_excel"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:299: in test_export_to_excel\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00026514400087762624, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_export_kpis_to_json", "lineno": 319, "outcome": "failed", "keywords": ["test_export_kpis_to_json", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00023368699476122856, "outcome": "passed"}, "call": {"duration": 0.027674730998114683, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 322, "message": "in test_export_kpis_to_json"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:322: in test_export_kpis_to_json\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00024373800260946155, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_html_report", "lineno": 349, "outcome": "failed", "keywords": ["test_generate_html_report", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00020942300034221262, "outcome": "passed"}, "call": {"duration": 0.0202566099978867, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 352, "message": "in test_generate_html_report"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:352: in test_generate_html_report\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00022248399909585714, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_pdf_report", "lineno": 379, "outcome": "failed", "keywords": ["test_generate_pdf_report", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00020686299831140786, "outcome": "passed"}, "call": {"duration": 0.021303404995705932, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 382, "message": "in test_generate_pdf_report"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:382: in test_generate_pdf_report\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0003563490026863292, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_complete_report_package", "lineno": 404, "outcome": "failed", "keywords": ["test_generate_complete_report_package", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.0003159729967592284, "outcome": "passed"}, "call": {"duration": 0.02693007900234079, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 407, "message": "in test_generate_complete_report_package"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:407: in test_generate_complete_report_package\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002442459954181686, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_executive_summary", "lineno": 443, "outcome": "failed", "keywords": ["test_generate_executive_summary", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00021965400082990527, "outcome": "passed"}, "call": {"duration": 0.020762640997418202, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 446, "message": "in test_generate_executive_summary"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:446: in test_generate_executive_summary\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002618650032673031, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_entity_breakdown_report", "lineno": 477, "outcome": "failed", "keywords": ["test_generate_entity_breakdown_report", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00024321900127688423, "outcome": "passed"}, "call": {"duration": 0.022129753000626806, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 480, "message": "in test_generate_entity_breakdown_report"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:480: in test_generate_entity_breakdown_report\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00025713100330904126, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_trend_analysis_report", "lineno": 510, "outcome": "failed", "keywords": ["test_generate_trend_analysis_report", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.0002163500030292198, "outcome": "passed"}, "call": {"duration": 0.02223288599634543, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 513, "message": "in test_generate_trend_analysis_report"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:513: in test_generate_trend_analysis_report\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002480179973645136, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_risk_assessment_report", "lineno": 541, "outcome": "failed", "keywords": ["test_generate_risk_assessment_report", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.0002257570013171062, "outcome": "passed"}, "call": {"duration": 0.02008612699864898, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 544, "message": "in test_generate_risk_assessment_report"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:544: in test_generate_risk_assessment_report\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00025074099539779127, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_scenario_comparison_report", "lineno": 574, "outcome": "failed", "keywords": ["test_generate_scenario_comparison_report", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00021902900334680453, "outcome": "passed"}, "call": {"duration": 0.019702171004610136, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 577, "message": "in test_generate_scenario_comparison_report"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:577: in test_generate_scenario_comparison_report\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0001992940015043132, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_generate_custom_report_template", "lineno": 623, "outcome": "failed", "keywords": ["test_generate_custom_report_template", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00019436699949437752, "outcome": "passed"}, "call": {"duration": 0.019479677997878753, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 626, "message": "in test_generate_custom_report_template"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:626: in test_generate_custom_report_template\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00024375299835810438, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_error_handling", "lineno": 683, "outcome": "failed", "keywords": ["test_report_error_handling", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00020367099932627752, "outcome": "passed"}, "call": {"duration": 0.019574222998926416, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 686, "message": "in test_report_error_handling"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:686: in test_report_error_handling\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00025846400239970535, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_customization_options", "lineno": 733, "outcome": "failed", "keywords": ["test_report_customization_options", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00024036800459725782, "outcome": "passed"}, "call": {"duration": 0.021116319992870558, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 736, "message": "in test_report_customization_options"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:736: in test_report_customization_options\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00024134300474543124, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_automation_and_scheduling", "lineno": 778, "outcome": "failed", "keywords": ["test_report_automation_and_scheduling", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00022568799613509327, "outcome": "passed"}, "call": {"duration": 0.025813558997469954, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 781, "message": "in test_report_automation_and_scheduling"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:781: in test_report_automation_and_scheduling\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002571930017438717, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_performance_optimization", "lineno": 816, "outcome": "failed", "keywords": ["test_report_performance_optimization", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.00021102999744471163, "outcome": "passed"}, "call": {"duration": 0.021576592000201344, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 819, "message": "in test_report_performance_optimization"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:819: in test_report_performance_optimization\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.0002390139998169616, "outcome": "passed"}}, {"nodeid": "tests/test_reports.py::TestReportGenerator::test_report_data_validation", "lineno": 880, "outcome": "failed", "keywords": ["test_report_data_validation", "TestReportGenerator", "test_reports.py", "tests", "cashcow", ""], "setup": {"duration": 0.0002152090019080788, "outcome": "passed"}, "call": {"duration": 0.02429423900321126, "outcome": "failed", "crash": {"path": "/home/alex/cashcow/tests/test_reports.py", "lineno": 32, "message": "TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "traceback": [{"path": "tests/test_reports.py", "lineno": 883, "message": "in test_report_data_validation"}, {"path": "tests/test_reports.py", "lineno": 32, "message": "in setUp"}], "longrepr": "tests/test_reports.py:883: in test_report_data_validation\n    self.setUp()\ntests/test_reports.py:32: in setUp\n    self.engine = CashFlowEngine(self.store, self.registry)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE   TypeError: CashFlowEngine.__init__() takes 2 positional arguments but 3 were given"}, "teardown": {"duration": 0.00031072599813342094, "outcome": "passed"}}]}